//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1SaveResponse
    {
        
        private ComporiPriceDataPriceListInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPriceDataPriceListInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool activeField;
        
        private bool activeFieldSpecified;
        
        private string codeField;
        
        private int websiteIdField;
        
        private bool websiteIdFieldSpecified;
        
        private string websiteCodeField;
        
        private string currencyCodeField;
        
        private string createdAtField;
        
        private string updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activeSpecified
        {
            get
            {
                return this.activeFieldSpecified;
            }
            set
            {
                this.activeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int websiteId
        {
            get
            {
                return this.websiteIdField;
            }
            set
            {
                this.websiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool websiteIdSpecified
        {
            get
            {
                return this.websiteIdFieldSpecified;
            }
            set
            {
                this.websiteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string websiteCode
        {
            get
            {
                return this.websiteCodeField;
            }
            set
            {
                this.websiteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string currencyCode
        {
            get
            {
                return this.currencyCodeField;
            }
            set
            {
                this.currencyCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string updatedAt
        {
            get
            {
                return this.updatedAtField;
            }
            set
            {
                this.updatedAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1SaveRequest
    {
        
        private ComporiPriceDataPriceListInterface priceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListInterface priceList
        {
            get
            {
                return this.priceListField;
            }
            set
            {
                this.priceListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPr" +
        "icePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType")]
    public interface comporiPricePriceListRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveResponse1> comporiPricePriceListRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdResponse1> comporiPricePriceListRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1Get", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1Get", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetResponse1> comporiPricePriceListRepositoryV1GetAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListResponse1> comporiPricePriceListRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteResponse1> comporiPricePriceListRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPricePriceListRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.GenericFault), Action="comporiPricePriceListRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdResponse1> comporiPricePriceListRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1SaveRequest comporiPricePriceListRepositoryV1SaveRequest;
        
        public comporiPricePriceListRepositoryV1SaveRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1SaveRequest comporiPricePriceListRepositoryV1SaveRequest)
        {
            this.comporiPricePriceListRepositoryV1SaveRequest = comporiPricePriceListRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1SaveResponse comporiPricePriceListRepositoryV1SaveResponse;
        
        public comporiPricePriceListRepositoryV1SaveResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1SaveResponse comporiPricePriceListRepositoryV1SaveResponse)
        {
            this.comporiPricePriceListRepositoryV1SaveResponse = comporiPricePriceListRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetByIdResponse
    {
        
        private ComporiPriceDataPriceListInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetByIdRequest comporiPricePriceListRepositoryV1GetByIdRequest;
        
        public comporiPricePriceListRepositoryV1GetByIdRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetByIdRequest comporiPricePriceListRepositoryV1GetByIdRequest)
        {
            this.comporiPricePriceListRepositoryV1GetByIdRequest = comporiPricePriceListRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetByIdResponse comporiPricePriceListRepositoryV1GetByIdResponse;
        
        public comporiPricePriceListRepositoryV1GetByIdResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetByIdResponse comporiPricePriceListRepositoryV1GetByIdResponse)
        {
            this.comporiPricePriceListRepositoryV1GetByIdResponse = comporiPricePriceListRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetRequest
    {
        
        private string codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetResponse
    {
        
        private ComporiPriceDataPriceListInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetRequest comporiPricePriceListRepositoryV1GetRequest;
        
        public comporiPricePriceListRepositoryV1GetRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetRequest comporiPricePriceListRepositoryV1GetRequest)
        {
            this.comporiPricePriceListRepositoryV1GetRequest = comporiPricePriceListRepositoryV1GetRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetResponse comporiPricePriceListRepositoryV1GetResponse;
        
        public comporiPricePriceListRepositoryV1GetResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetResponse comporiPricePriceListRepositoryV1GetResponse)
        {
            this.comporiPricePriceListRepositoryV1GetResponse = comporiPricePriceListRepositoryV1GetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1GetListResponse
    {
        
        private ComporiPriceDataPriceListSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPriceDataPriceListSearchResultsInterface
    {
        
        private ComporiPriceDataPriceListInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataPriceListInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetListRequest comporiPricePriceListRepositoryV1GetListRequest;
        
        public comporiPricePriceListRepositoryV1GetListRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetListRequest comporiPricePriceListRepositoryV1GetListRequest)
        {
            this.comporiPricePriceListRepositoryV1GetListRequest = comporiPricePriceListRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetListResponse comporiPricePriceListRepositoryV1GetListResponse;
        
        public comporiPricePriceListRepositoryV1GetListResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetListResponse comporiPricePriceListRepositoryV1GetListResponse)
        {
            this.comporiPricePriceListRepositoryV1GetListResponse = comporiPricePriceListRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1DeleteRequest
    {
        
        private ComporiPriceDataPriceListInterface priceListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataPriceListInterface priceList
        {
            get
            {
                return this.priceListField;
            }
            set
            {
                this.priceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1DeleteResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteRequest comporiPricePriceListRepositoryV1DeleteRequest;
        
        public comporiPricePriceListRepositoryV1DeleteRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1DeleteRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteRequest comporiPricePriceListRepositoryV1DeleteRequest)
        {
            this.comporiPricePriceListRepositoryV1DeleteRequest = comporiPricePriceListRepositoryV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteResponse comporiPricePriceListRepositoryV1DeleteResponse;
        
        public comporiPricePriceListRepositoryV1DeleteResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1DeleteResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteResponse comporiPricePriceListRepositoryV1DeleteResponse)
        {
            this.comporiPricePriceListRepositoryV1DeleteResponse = comporiPricePriceListRepositoryV1DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
        "stRepositoryV1")]
    public partial class ComporiPricePriceListRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteByIdRequest comporiPricePriceListRepositoryV1DeleteByIdRequest;
        
        public comporiPricePriceListRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public comporiPricePriceListRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteByIdRequest comporiPricePriceListRepositoryV1DeleteByIdRequest)
        {
            this.comporiPricePriceListRepositoryV1DeleteByIdRequest = comporiPricePriceListRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPricePriceListRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
            "stRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteByIdResponse comporiPricePriceListRepositoryV1DeleteByIdResponse;
        
        public comporiPricePriceListRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public comporiPricePriceListRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteByIdResponse comporiPricePriceListRepositoryV1DeleteByIdResponse)
        {
            this.comporiPricePriceListRepositoryV1DeleteByIdResponse = comporiPricePriceListRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface comporiPricePriceListRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class comporiPricePriceListRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comporiPricePriceListRepositoryV1PortTypeClient() : 
                base(comporiPricePriceListRepositoryV1PortTypeClient.GetDefaultBinding(), comporiPricePriceListRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.comporiPricePriceListRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPricePriceListRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(comporiPricePriceListRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), comporiPricePriceListRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPricePriceListRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comporiPricePriceListRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPricePriceListRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comporiPricePriceListRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPricePriceListRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveResponse1> comporiPricePriceListRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1SaveRequest comporiPricePriceListRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1SaveRequest1();
            inValue.comporiPricePriceListRepositoryV1SaveRequest = comporiPricePriceListRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdResponse1> comporiPricePriceListRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetByIdRequest comporiPricePriceListRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetByIdRequest1();
            inValue.comporiPricePriceListRepositoryV1GetByIdRequest = comporiPricePriceListRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1GetAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetResponse1> comporiPricePriceListRepositoryV1GetAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetRequest comporiPricePriceListRepositoryV1GetRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetRequest1();
            inValue.comporiPricePriceListRepositoryV1GetRequest = comporiPricePriceListRepositoryV1GetRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListResponse1> comporiPricePriceListRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1GetListRequest comporiPricePriceListRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1GetListRequest1();
            inValue.comporiPricePriceListRepositoryV1GetListRequest = comporiPricePriceListRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteResponse1> comporiPricePriceListRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteRequest comporiPricePriceListRepositoryV1DeleteRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteRequest1();
            inValue.comporiPricePriceListRepositoryV1DeleteRequest = comporiPricePriceListRepositoryV1DeleteRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType.comporiPricePriceListRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.comporiPricePriceListRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdResponse1> comporiPricePriceListRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.ComporiPricePriceListRepositoryV1DeleteByIdRequest comporiPricePriceListRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1DeleteByIdRequest1();
            inValue.comporiPricePriceListRepositoryV1DeleteByIdRequest = comporiPricePriceListRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPricePriceListRepositoryV1.comporiPricePriceListRepositoryV1PortType)(this)).comporiPricePriceListRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPricePriceListRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPricePriceListRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPricePriceLi" +
                        "stRepositoryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return comporiPricePriceListRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.comporiPricePriceListRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return comporiPricePriceListRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.comporiPricePriceListRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            comporiPricePriceListRepositoryV1Port,
        }
    }
}
