//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1SaveResponse
    {
        
        private ComporiPriceDataDiscountInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDataDiscountInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool activeField;
        
        private string codeField;
        
        private string nameField;
        
        private int websiteIdField;
        
        private bool websiteIdFieldSpecified;
        
        private string websiteCodeField;
        
        private int positionField;
        
        private float quantityField;
        
        private bool quantityFieldSpecified;
        
        private float valueField;
        
        private string validFromField;
        
        private string validToField;
        
        private int groupIdField;
        
        private bool groupIdFieldSpecified;
        
        private string groupCodeField;
        
        private string createdAtField;
        
        private string updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int websiteId
        {
            get
            {
                return this.websiteIdField;
            }
            set
            {
                this.websiteIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool websiteIdSpecified
        {
            get
            {
                return this.websiteIdFieldSpecified;
            }
            set
            {
                this.websiteIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string websiteCode
        {
            get
            {
                return this.websiteCodeField;
            }
            set
            {
                this.websiteCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public float quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantitySpecified
        {
            get
            {
                return this.quantityFieldSpecified;
            }
            set
            {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string validFrom
        {
            get
            {
                return this.validFromField;
            }
            set
            {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string validTo
        {
            get
            {
                return this.validToField;
            }
            set
            {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int groupId
        {
            get
            {
                return this.groupIdField;
            }
            set
            {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool groupIdSpecified
        {
            get
            {
                return this.groupIdFieldSpecified;
            }
            set
            {
                this.groupIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string groupCode
        {
            get
            {
                return this.groupCodeField;
            }
            set
            {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string updatedAt
        {
            get
            {
                return this.updatedAtField;
            }
            set
            {
                this.updatedAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1SaveRequest
    {
        
        private ComporiPriceDataDiscountInterface discountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountInterface discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPr" +
        "iceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType")]
    public interface comporiPriceDiscountRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.GenericFault), Action="comporiPriceDiscountRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveResponse1> comporiPriceDiscountRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.GenericFault), Action="comporiPriceDiscountRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdResponse1> comporiPriceDiscountRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.GenericFault), Action="comporiPriceDiscountRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListResponse1> comporiPriceDiscountRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountRepositoryV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.GenericFault), Action="comporiPriceDiscountRepositoryV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteResponse1> comporiPriceDiscountRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.GenericFault), Action="comporiPriceDiscountRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdResponse1> comporiPriceDiscountRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1SaveRequest comporiPriceDiscountRepositoryV1SaveRequest;
        
        public comporiPriceDiscountRepositoryV1SaveRequest1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1SaveRequest comporiPriceDiscountRepositoryV1SaveRequest)
        {
            this.comporiPriceDiscountRepositoryV1SaveRequest = comporiPriceDiscountRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1SaveResponse comporiPriceDiscountRepositoryV1SaveResponse;
        
        public comporiPriceDiscountRepositoryV1SaveResponse1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1SaveResponse comporiPriceDiscountRepositoryV1SaveResponse)
        {
            this.comporiPriceDiscountRepositoryV1SaveResponse = comporiPriceDiscountRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1GetByIdResponse
    {
        
        private ComporiPriceDataDiscountInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetByIdRequest comporiPriceDiscountRepositoryV1GetByIdRequest;
        
        public comporiPriceDiscountRepositoryV1GetByIdRequest1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetByIdRequest comporiPriceDiscountRepositoryV1GetByIdRequest)
        {
            this.comporiPriceDiscountRepositoryV1GetByIdRequest = comporiPriceDiscountRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetByIdResponse comporiPriceDiscountRepositoryV1GetByIdResponse;
        
        public comporiPriceDiscountRepositoryV1GetByIdResponse1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetByIdResponse comporiPriceDiscountRepositoryV1GetByIdResponse)
        {
            this.comporiPriceDiscountRepositoryV1GetByIdResponse = comporiPriceDiscountRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1GetListResponse
    {
        
        private ComporiPriceDataDiscountSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDataDiscountSearchResultsInterface
    {
        
        private ComporiPriceDataDiscountInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetListRequest comporiPriceDiscountRepositoryV1GetListRequest;
        
        public comporiPriceDiscountRepositoryV1GetListRequest1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetListRequest comporiPriceDiscountRepositoryV1GetListRequest)
        {
            this.comporiPriceDiscountRepositoryV1GetListRequest = comporiPriceDiscountRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetListResponse comporiPriceDiscountRepositoryV1GetListResponse;
        
        public comporiPriceDiscountRepositoryV1GetListResponse1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetListResponse comporiPriceDiscountRepositoryV1GetListResponse)
        {
            this.comporiPriceDiscountRepositoryV1GetListResponse = comporiPriceDiscountRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1DeleteRequest
    {
        
        private ComporiPriceDataDiscountInterface discountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountInterface discount
        {
            get
            {
                return this.discountField;
            }
            set
            {
                this.discountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1DeleteResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteRequest comporiPriceDiscountRepositoryV1DeleteRequest;
        
        public comporiPriceDiscountRepositoryV1DeleteRequest1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1DeleteRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteRequest comporiPriceDiscountRepositoryV1DeleteRequest)
        {
            this.comporiPriceDiscountRepositoryV1DeleteRequest = comporiPriceDiscountRepositoryV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteResponse comporiPriceDiscountRepositoryV1DeleteResponse;
        
        public comporiPriceDiscountRepositoryV1DeleteResponse1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1DeleteResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteResponse comporiPriceDiscountRepositoryV1DeleteResponse)
        {
            this.comporiPriceDiscountRepositoryV1DeleteResponse = comporiPriceDiscountRepositoryV1DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tRepositoryV1")]
    public partial class ComporiPriceDiscountRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteByIdRequest comporiPriceDiscountRepositoryV1DeleteByIdRequest;
        
        public comporiPriceDiscountRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteByIdRequest comporiPriceDiscountRepositoryV1DeleteByIdRequest)
        {
            this.comporiPriceDiscountRepositoryV1DeleteByIdRequest = comporiPriceDiscountRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteByIdResponse comporiPriceDiscountRepositoryV1DeleteByIdResponse;
        
        public comporiPriceDiscountRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public comporiPriceDiscountRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteByIdResponse comporiPriceDiscountRepositoryV1DeleteByIdResponse)
        {
            this.comporiPriceDiscountRepositoryV1DeleteByIdResponse = comporiPriceDiscountRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface comporiPriceDiscountRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class comporiPriceDiscountRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comporiPriceDiscountRepositoryV1PortTypeClient() : 
                base(comporiPriceDiscountRepositoryV1PortTypeClient.GetDefaultBinding(), comporiPriceDiscountRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.comporiPriceDiscountRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(comporiPriceDiscountRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), comporiPriceDiscountRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comporiPriceDiscountRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comporiPriceDiscountRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType.comporiPriceDiscountRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveRequest1 request)
        {
            return base.Channel.comporiPriceDiscountRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveResponse1> comporiPriceDiscountRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1SaveRequest comporiPriceDiscountRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1SaveRequest1();
            inValue.comporiPriceDiscountRepositoryV1SaveRequest = comporiPriceDiscountRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType)(this)).comporiPriceDiscountRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType.comporiPriceDiscountRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdResponse1> comporiPriceDiscountRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetByIdRequest comporiPriceDiscountRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetByIdRequest1();
            inValue.comporiPriceDiscountRepositoryV1GetByIdRequest = comporiPriceDiscountRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType)(this)).comporiPriceDiscountRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType.comporiPriceDiscountRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListRequest1 request)
        {
            return base.Channel.comporiPriceDiscountRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListResponse1> comporiPriceDiscountRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1GetListRequest comporiPriceDiscountRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1GetListRequest1();
            inValue.comporiPriceDiscountRepositoryV1GetListRequest = comporiPriceDiscountRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType)(this)).comporiPriceDiscountRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType.comporiPriceDiscountRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteRequest1 request)
        {
            return base.Channel.comporiPriceDiscountRepositoryV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteResponse1> comporiPriceDiscountRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteRequest comporiPriceDiscountRepositoryV1DeleteRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteRequest1();
            inValue.comporiPriceDiscountRepositoryV1DeleteRequest = comporiPriceDiscountRepositoryV1DeleteRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType)(this)).comporiPriceDiscountRepositoryV1DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType.comporiPriceDiscountRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdResponse1> comporiPriceDiscountRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.ComporiPriceDiscountRepositoryV1DeleteByIdRequest comporiPriceDiscountRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1DeleteByIdRequest1();
            inValue.comporiPriceDiscountRepositoryV1DeleteByIdRequest = comporiPriceDiscountRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountRepositoryV1.comporiPriceDiscountRepositoryV1PortType)(this)).comporiPriceDiscountRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
                        "tRepositoryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return comporiPriceDiscountRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.comporiPriceDiscountRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return comporiPriceDiscountRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.comporiPriceDiscountRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            comporiPriceDiscountRepositoryV1Port,
        }
    }
}
