//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1SaveResponse
    {
        
        private ComporiPriceDataDiscountProductInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDataDiscountProductInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int productIdField;
        
        private bool productIdFieldSpecified;
        
        private string productSkuField;
        
        private int discountIdField;
        
        private bool discountIdFieldSpecified;
        
        private string discountCodeField;
        
        private string createdAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int productId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool productIdSpecified
        {
            get
            {
                return this.productIdFieldSpecified;
            }
            set
            {
                this.productIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productSku
        {
            get
            {
                return this.productSkuField;
            }
            set
            {
                this.productSkuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int discountId
        {
            get
            {
                return this.discountIdField;
            }
            set
            {
                this.discountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountIdSpecified
        {
            get
            {
                return this.discountIdFieldSpecified;
            }
            set
            {
                this.discountIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string discountCode
        {
            get
            {
                return this.discountCodeField;
            }
            set
            {
                this.discountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1SaveRequest
    {
        
        private ComporiPriceDataDiscountProductInterface discountProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductInterface discountProduct
        {
            get
            {
                return this.discountProductField;
            }
            set
            {
                this.discountProductField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPr" +
        "iceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType")]
    public interface comporiPriceDiscountProductRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveResponse1> comporiPriceDiscountProductRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1SaveBulk", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1SaveBulk", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkResponse1> comporiPriceDiscountProductRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdResponse1> comporiPriceDiscountProductRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListResponse1> comporiPriceDiscountProductRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteResponse1> comporiPriceDiscountProductRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.GenericFault), Action="comporiPriceDiscountProductRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1> comporiPriceDiscountProductRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveRequest comporiPriceDiscountProductRepositoryV1SaveRequest;
        
        public comporiPriceDiscountProductRepositoryV1SaveRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveRequest comporiPriceDiscountProductRepositoryV1SaveRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1SaveRequest = comporiPriceDiscountProductRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveResponse comporiPriceDiscountProductRepositoryV1SaveResponse;
        
        public comporiPriceDiscountProductRepositoryV1SaveResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveResponse comporiPriceDiscountProductRepositoryV1SaveResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1SaveResponse = comporiPriceDiscountProductRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1SaveBulkRequest
    {
        
        private ComporiPriceDataDiscountSaveProductBulkInterface[] discountProductsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountSaveProductBulkInterface[] discountProducts
        {
            get
            {
                return this.discountProductsField;
            }
            set
            {
                this.discountProductsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDataDiscountSaveProductBulkInterface
    {
        
        private int sequenceField;
        
        private bool succeededField;
        
        private bool succeededFieldSpecified;
        
        private string messageField;
        
        private ComporiPriceDataDiscountProductInterface discountProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool succeeded
        {
            get
            {
                return this.succeededField;
            }
            set
            {
                this.succeededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool succeededSpecified
        {
            get
            {
                return this.succeededFieldSpecified;
            }
            set
            {
                this.succeededFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ComporiPriceDataDiscountProductInterface discountProduct
        {
            get
            {
                return this.discountProductField;
            }
            set
            {
                this.discountProductField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1SaveBulkResponse
    {
        
        private ComporiPriceDataDiscountSaveProductBulkInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountSaveProductBulkInterface[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1SaveBulkRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveBulkRequest comporiPriceDiscountProductRepositoryV1SaveBulkRequest;
        
        public comporiPriceDiscountProductRepositoryV1SaveBulkRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1SaveBulkRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveBulkRequest comporiPriceDiscountProductRepositoryV1SaveBulkRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1SaveBulkRequest = comporiPriceDiscountProductRepositoryV1SaveBulkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1SaveBulkResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveBulkResponse comporiPriceDiscountProductRepositoryV1SaveBulkResponse;
        
        public comporiPriceDiscountProductRepositoryV1SaveBulkResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1SaveBulkResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveBulkResponse comporiPriceDiscountProductRepositoryV1SaveBulkResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1SaveBulkResponse = comporiPriceDiscountProductRepositoryV1SaveBulkResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1GetByIdResponse
    {
        
        private ComporiPriceDataDiscountProductInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetByIdRequest comporiPriceDiscountProductRepositoryV1GetByIdRequest;
        
        public comporiPriceDiscountProductRepositoryV1GetByIdRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetByIdRequest comporiPriceDiscountProductRepositoryV1GetByIdRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1GetByIdRequest = comporiPriceDiscountProductRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetByIdResponse comporiPriceDiscountProductRepositoryV1GetByIdResponse;
        
        public comporiPriceDiscountProductRepositoryV1GetByIdResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetByIdResponse comporiPriceDiscountProductRepositoryV1GetByIdResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1GetByIdResponse = comporiPriceDiscountProductRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1GetListResponse
    {
        
        private ComporiPriceDataDiscountProductSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDataDiscountProductSearchResultsInterface
    {
        
        private ComporiPriceDataDiscountProductInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountProductInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetListRequest comporiPriceDiscountProductRepositoryV1GetListRequest;
        
        public comporiPriceDiscountProductRepositoryV1GetListRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetListRequest comporiPriceDiscountProductRepositoryV1GetListRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1GetListRequest = comporiPriceDiscountProductRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetListResponse comporiPriceDiscountProductRepositoryV1GetListResponse;
        
        public comporiPriceDiscountProductRepositoryV1GetListResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetListResponse comporiPriceDiscountProductRepositoryV1GetListResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1GetListResponse = comporiPriceDiscountProductRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1DeleteRequest
    {
        
        private ComporiPriceDataDiscountProductInterface discountProductField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductInterface discountProduct
        {
            get
            {
                return this.discountProductField;
            }
            set
            {
                this.discountProductField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1DeleteResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteRequest comporiPriceDiscountProductRepositoryV1DeleteRequest;
        
        public comporiPriceDiscountProductRepositoryV1DeleteRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1DeleteRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteRequest comporiPriceDiscountProductRepositoryV1DeleteRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1DeleteRequest = comporiPriceDiscountProductRepositoryV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteResponse comporiPriceDiscountProductRepositoryV1DeleteResponse;
        
        public comporiPriceDiscountProductRepositoryV1DeleteResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1DeleteResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteResponse comporiPriceDiscountProductRepositoryV1DeleteResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1DeleteResponse = comporiPriceDiscountProductRepositoryV1DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductRepositoryV1")]
    public partial class ComporiPriceDiscountProductRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteByIdRequest comporiPriceDiscountProductRepositoryV1DeleteByIdRequest;
        
        public comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteByIdRequest comporiPriceDiscountProductRepositoryV1DeleteByIdRequest)
        {
            this.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest = comporiPriceDiscountProductRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteByIdResponse comporiPriceDiscountProductRepositoryV1DeleteByIdResponse;
        
        public comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteByIdResponse comporiPriceDiscountProductRepositoryV1DeleteByIdResponse)
        {
            this.comporiPriceDiscountProductRepositoryV1DeleteByIdResponse = comporiPriceDiscountProductRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface comporiPriceDiscountProductRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class comporiPriceDiscountProductRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comporiPriceDiscountProductRepositoryV1PortTypeClient() : 
                base(comporiPriceDiscountProductRepositoryV1PortTypeClient.GetDefaultBinding(), comporiPriceDiscountProductRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.comporiPriceDiscountProductRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(comporiPriceDiscountProductRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), comporiPriceDiscountProductRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comporiPriceDiscountProductRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comporiPriceDiscountProductRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveResponse1> comporiPriceDiscountProductRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveRequest comporiPriceDiscountProductRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1SaveRequest = comporiPriceDiscountProductRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1SaveBulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkResponse1> comporiPriceDiscountProductRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1SaveBulkRequest comporiPriceDiscountProductRepositoryV1SaveBulkRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1SaveBulkRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1SaveBulkRequest = comporiPriceDiscountProductRepositoryV1SaveBulkRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1SaveBulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdResponse1> comporiPriceDiscountProductRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetByIdRequest comporiPriceDiscountProductRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetByIdRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1GetByIdRequest = comporiPriceDiscountProductRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListResponse1> comporiPriceDiscountProductRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1GetListRequest comporiPriceDiscountProductRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1GetListRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1GetListRequest = comporiPriceDiscountProductRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteResponse1> comporiPriceDiscountProductRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteRequest comporiPriceDiscountProductRepositoryV1DeleteRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1DeleteRequest = comporiPriceDiscountProductRepositoryV1DeleteRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType.comporiPriceDiscountProductRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdResponse1> comporiPriceDiscountProductRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.ComporiPriceDiscountProductRepositoryV1DeleteByIdRequest comporiPriceDiscountProductRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest1();
            inValue.comporiPriceDiscountProductRepositoryV1DeleteByIdRequest = comporiPriceDiscountProductRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductRepositoryV1.comporiPriceDiscountProductRepositoryV1PortType)(this)).comporiPriceDiscountProductRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountProductRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountProductRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
                        "tProductRepositoryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return comporiPriceDiscountProductRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.comporiPriceDiscountProductRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return comporiPriceDiscountProductRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.comporiPriceDiscountProductRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            comporiPriceDiscountProductRepositoryV1Port,
        }
    }
}
