//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1SaveResponse
    {
        
        private ComporiPriceDataDiscountProductGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductGroupInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDataDiscountProductGroupInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string codeField;
        
        private string nameField;
        
        private string createdAtField;
        
        private string updatedAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string updatedAt
        {
            get
            {
                return this.updatedAtField;
            }
            set
            {
                this.updatedAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1SaveRequest
    {
        
        private ComporiPriceDataDiscountProductGroupInterface groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductGroupInterface group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPr" +
        "iceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1" +
        "PortType")]
    public interface comporiPriceDiscountProductGroupRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductGroupRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.GenericFault), Action="comporiPriceDiscountProductGroupRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveResponse1> comporiPriceDiscountProductGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductGroupRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.GenericFault), Action="comporiPriceDiscountProductGroupRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1> comporiPriceDiscountProductGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductGroupRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.GenericFault), Action="comporiPriceDiscountProductGroupRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListResponse1> comporiPriceDiscountProductGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductGroupRepositoryV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.GenericFault), Action="comporiPriceDiscountProductGroupRepositoryV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1> comporiPriceDiscountProductGroupRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountProductGroupRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.GenericFault), Action="comporiPriceDiscountProductGroupRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1> comporiPriceDiscountProductGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1SaveRequest comporiPriceDiscountProductGroupRepositoryV1SaveRequest;
        
        public comporiPriceDiscountProductGroupRepositoryV1SaveRequest1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1SaveRequest comporiPriceDiscountProductGroupRepositoryV1SaveRequest)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1SaveRequest = comporiPriceDiscountProductGroupRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1SaveResponse comporiPriceDiscountProductGroupRepositoryV1SaveResponse;
        
        public comporiPriceDiscountProductGroupRepositoryV1SaveResponse1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1SaveResponse comporiPriceDiscountProductGroupRepositoryV1SaveResponse)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1SaveResponse = comporiPriceDiscountProductGroupRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1GetByIdResponse
    {
        
        private ComporiPriceDataDiscountProductGroupInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductGroupInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetByIdRequest comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest;
        
        public comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetByIdRequest comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest = comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetByIdResponse comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse;
        
        public comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetByIdResponse comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse = comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1GetListResponse
    {
        
        private ComporiPriceDataDiscountProductGroupSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductGroupSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDataDiscountProductGroupSearchResultsInterface
    {
        
        private ComporiPriceDataDiscountProductGroupInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountProductGroupInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetListRequest comporiPriceDiscountProductGroupRepositoryV1GetListRequest;
        
        public comporiPriceDiscountProductGroupRepositoryV1GetListRequest1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetListRequest comporiPriceDiscountProductGroupRepositoryV1GetListRequest)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1GetListRequest = comporiPriceDiscountProductGroupRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetListResponse comporiPriceDiscountProductGroupRepositoryV1GetListResponse;
        
        public comporiPriceDiscountProductGroupRepositoryV1GetListResponse1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetListResponse comporiPriceDiscountProductGroupRepositoryV1GetListResponse)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1GetListResponse = comporiPriceDiscountProductGroupRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1DeleteRequest
    {
        
        private ComporiPriceDataDiscountProductGroupInterface groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountProductGroupInterface group
        {
            get
            {
                return this.groupField;
            }
            set
            {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1DeleteResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteRequest comporiPriceDiscountProductGroupRepositoryV1DeleteRequest;
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteRequest comporiPriceDiscountProductGroupRepositoryV1DeleteRequest)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest = comporiPriceDiscountProductGroupRepositoryV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteResponse comporiPriceDiscountProductGroupRepositoryV1DeleteResponse;
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteResponse comporiPriceDiscountProductGroupRepositoryV1DeleteResponse)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1DeleteResponse = comporiPriceDiscountProductGroupRepositoryV1DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tProductGroupRepositoryV1")]
    public partial class ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest;
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest = comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tProductGroupRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse;
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse)
        {
            this.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse = comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface comporiPriceDiscountProductGroupRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class comporiPriceDiscountProductGroupRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comporiPriceDiscountProductGroupRepositoryV1PortTypeClient() : 
                base(comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetDefaultBinding(), comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.comporiPriceDiscountProductGroupRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountProductGroupRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType.comporiPriceDiscountProductGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductGroupRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveResponse1> comporiPriceDiscountProductGroupRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1SaveRequest comporiPriceDiscountProductGroupRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1SaveRequest1();
            inValue.comporiPriceDiscountProductGroupRepositoryV1SaveRequest = comporiPriceDiscountProductGroupRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType)(this)).comporiPriceDiscountProductGroupRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType.comporiPriceDiscountProductGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductGroupRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdResponse1> comporiPriceDiscountProductGroupRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetByIdRequest comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest1();
            inValue.comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest = comporiPriceDiscountProductGroupRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType)(this)).comporiPriceDiscountProductGroupRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType.comporiPriceDiscountProductGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductGroupRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListResponse1> comporiPriceDiscountProductGroupRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1GetListRequest comporiPriceDiscountProductGroupRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1GetListRequest1();
            inValue.comporiPriceDiscountProductGroupRepositoryV1GetListRequest = comporiPriceDiscountProductGroupRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType)(this)).comporiPriceDiscountProductGroupRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType.comporiPriceDiscountProductGroupRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductGroupRepositoryV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteResponse1> comporiPriceDiscountProductGroupRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteRequest comporiPriceDiscountProductGroupRepositoryV1DeleteRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest1();
            inValue.comporiPriceDiscountProductGroupRepositoryV1DeleteRequest = comporiPriceDiscountProductGroupRepositoryV1DeleteRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType)(this)).comporiPriceDiscountProductGroupRepositoryV1DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdResponse1> comporiPriceDiscountProductGroupRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.ComporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest1();
            inValue.comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest = comporiPriceDiscountProductGroupRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountProductGroupRepositoryV1.comporiPriceDiscountProductGroupRepositoryV1PortType)(this)).comporiPriceDiscountProductGroupRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountProductGroupRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountProductGroupRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
                        "tProductGroupRepositoryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.comporiPriceDiscountProductGroupRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return comporiPriceDiscountProductGroupRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.comporiPriceDiscountProductGroupRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            comporiPriceDiscountProductGroupRepositoryV1Port,
        }
    }
}
