//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class GenericFault
    {
        
        private string traceField;
        
        private GenericFaultParameter[] parametersField;
        
        private WrappedError[] wrappedErrorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Trace
        {
            get
            {
                return this.traceField;
            }
            set
            {
                this.traceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] Parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public WrappedError[] WrappedErrors
        {
            get
            {
                return this.wrappedErrorsField;
            }
            set
            {
                this.wrappedErrorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class GenericFaultParameter
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class WrappedError
    {
        
        private string messageField;
        
        private GenericFaultParameter[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public GenericFaultParameter[] parameters
        {
            get
            {
                return this.parametersField;
            }
            set
            {
                this.parametersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1SaveResponse
    {
        
        private ComporiPriceDataDiscountCustomerInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountCustomerInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDataDiscountCustomerInterface
    {
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int discountIdField;
        
        private bool discountIdFieldSpecified;
        
        private string discountCodeField;
        
        private int customerIdField;
        
        private bool customerIdFieldSpecified;
        
        private string createdAtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int discountId
        {
            get
            {
                return this.discountIdField;
            }
            set
            {
                this.discountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool discountIdSpecified
        {
            get
            {
                return this.discountIdFieldSpecified;
            }
            set
            {
                this.discountIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string discountCode
        {
            get
            {
                return this.discountCodeField;
            }
            set
            {
                this.discountCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool customerIdSpecified
        {
            get
            {
                return this.customerIdFieldSpecified;
            }
            set
            {
                this.customerIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string createdAt
        {
            get
            {
                return this.createdAtField;
            }
            set
            {
                this.createdAtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1SaveRequest
    {
        
        private ComporiPriceDataDiscountCustomerInterface discountCustomerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountCustomerInterface discountCustomer
        {
            get
            {
                return this.discountCustomerField;
            }
            set
            {
                this.discountCustomerField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1", ConfigurationName="Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPr" +
        "iceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType" +
        "")]
    public interface comporiPriceDiscountCustomerRepositoryV1PortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1Save", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1Save", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveResponse1> comporiPriceDiscountCustomerRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1SaveBulk", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1SaveBulk", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1> comporiPriceDiscountCustomerRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1GetById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1GetById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1> comporiPriceDiscountCustomerRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1GetList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1GetList", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListResponse1> comporiPriceDiscountCustomerRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1Delete", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1Delete", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteResponse1> comporiPriceDiscountCustomerRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="comporiPriceDiscountCustomerRepositoryV1DeleteById", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.GenericFault), Action="comporiPriceDiscountCustomerRepositoryV1DeleteById", Name="GenericFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1> comporiPriceDiscountCustomerRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1SaveRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveRequest comporiPriceDiscountCustomerRepositoryV1SaveRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1SaveRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1SaveRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveRequest comporiPriceDiscountCustomerRepositoryV1SaveRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1SaveRequest = comporiPriceDiscountCustomerRepositoryV1SaveRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1SaveResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveResponse comporiPriceDiscountCustomerRepositoryV1SaveResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1SaveResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1SaveResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveResponse comporiPriceDiscountCustomerRepositoryV1SaveResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1SaveResponse = comporiPriceDiscountCustomerRepositoryV1SaveResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1SaveBulkRequest
    {
        
        private ComporiPriceDataDiscountSaveCustomerBulkInterface[] discountCustomersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountSaveCustomerBulkInterface[] discountCustomers
        {
            get
            {
                return this.discountCustomersField;
            }
            set
            {
                this.discountCustomersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDataDiscountSaveCustomerBulkInterface
    {
        
        private int sequenceField;
        
        private bool succeededField;
        
        private bool succeededFieldSpecified;
        
        private string messageField;
        
        private ComporiPriceDataDiscountCustomerInterface discountCustomerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int sequence
        {
            get
            {
                return this.sequenceField;
            }
            set
            {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool succeeded
        {
            get
            {
                return this.succeededField;
            }
            set
            {
                this.succeededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool succeededSpecified
        {
            get
            {
                return this.succeededFieldSpecified;
            }
            set
            {
                this.succeededFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ComporiPriceDataDiscountCustomerInterface discountCustomer
        {
            get
            {
                return this.discountCustomerField;
            }
            set
            {
                this.discountCustomerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1SaveBulkResponse
    {
        
        private ComporiPriceDataDiscountSaveCustomerBulkInterface[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountSaveCustomerBulkInterface[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveBulkRequest comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveBulkRequest comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest = comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveBulkResponse comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveBulkResponse comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse = comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1GetByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1GetByIdResponse
    {
        
        private ComporiPriceDataDiscountCustomerInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountCustomerInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetByIdRequest comporiPriceDiscountCustomerRepositoryV1GetByIdRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetByIdRequest comporiPriceDiscountCustomerRepositoryV1GetByIdRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest = comporiPriceDiscountCustomerRepositoryV1GetByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetByIdResponse comporiPriceDiscountCustomerRepositoryV1GetByIdResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetByIdResponse comporiPriceDiscountCustomerRepositoryV1GetByIdResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1GetByIdResponse = comporiPriceDiscountCustomerRepositoryV1GetByIdResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1GetListRequest
    {
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class FrameworkSearchCriteriaInterface
    {
        
        private FrameworkSearchFilterGroup[] filterGroupsField;
        
        private FrameworkSortOrder[] sortOrdersField;
        
        private int pageSizeField;
        
        private bool pageSizeFieldSpecified;
        
        private int currentPageField;
        
        private bool currentPageFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSearchFilterGroup[] filterGroups
        {
            get
            {
                return this.filterGroupsField;
            }
            set
            {
                this.filterGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkSortOrder[] sortOrders
        {
            get
            {
                return this.sortOrdersField;
            }
            set
            {
                this.sortOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pageSizeSpecified
        {
            get
            {
                return this.pageSizeFieldSpecified;
            }
            set
            {
                this.pageSizeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int currentPage
        {
            get
            {
                return this.currentPageField;
            }
            set
            {
                this.currentPageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currentPageSpecified
        {
            get
            {
                return this.currentPageFieldSpecified;
            }
            set
            {
                this.currentPageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class FrameworkSearchFilterGroup
    {
        
        private FrameworkFilter[] filtersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public FrameworkFilter[] filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class FrameworkFilter
    {
        
        private string fieldField;
        
        private string valueField;
        
        private string conditionTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string conditionType
        {
            get
            {
                return this.conditionTypeField;
            }
            set
            {
                this.conditionTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class FrameworkSortOrder
    {
        
        private string fieldField;
        
        private string directionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direction
        {
            get
            {
                return this.directionField;
            }
            set
            {
                this.directionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1GetListResponse
    {
        
        private ComporiPriceDataDiscountCustomerSearchResultsInterface resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountCustomerSearchResultsInterface result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDataDiscountCustomerSearchResultsInterface
    {
        
        private ComporiPriceDataDiscountCustomerInterface[] itemsField;
        
        private FrameworkSearchCriteriaInterface searchCriteriaField;
        
        private int totalCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ComporiPriceDataDiscountCustomerInterface[] items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public FrameworkSearchCriteriaInterface searchCriteria
        {
            get
            {
                return this.searchCriteriaField;
            }
            set
            {
                this.searchCriteriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int totalCount
        {
            get
            {
                return this.totalCountField;
            }
            set
            {
                this.totalCountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1GetListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetListRequest comporiPriceDiscountCustomerRepositoryV1GetListRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1GetListRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1GetListRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetListRequest comporiPriceDiscountCustomerRepositoryV1GetListRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1GetListRequest = comporiPriceDiscountCustomerRepositoryV1GetListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1GetListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetListResponse comporiPriceDiscountCustomerRepositoryV1GetListResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1GetListResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1GetListResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetListResponse comporiPriceDiscountCustomerRepositoryV1GetListResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1GetListResponse = comporiPriceDiscountCustomerRepositoryV1GetListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1DeleteRequest
    {
        
        private ComporiPriceDataDiscountCustomerInterface discountCustomerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ComporiPriceDataDiscountCustomerInterface discountCustomer
        {
            get
            {
                return this.discountCustomerField;
            }
            set
            {
                this.discountCustomerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1DeleteResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteRequest comporiPriceDiscountCustomerRepositoryV1DeleteRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteRequest comporiPriceDiscountCustomerRepositoryV1DeleteRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1DeleteRequest = comporiPriceDiscountCustomerRepositoryV1DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteResponse comporiPriceDiscountCustomerRepositoryV1DeleteResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteResponse comporiPriceDiscountCustomerRepositoryV1DeleteResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1DeleteResponse = comporiPriceDiscountCustomerRepositoryV1DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest
    {
        
        private int idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
        "tCustomerRepositoryV1")]
    public partial class ComporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse
    {
        
        private bool resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest;
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest)
        {
            this.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest = comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
            "tCustomerRepositoryV1", Order=0)]
        public Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse;
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1()
        {
        }
        
        public comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse)
        {
            this.comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse = comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public interface comporiPriceDiscountCustomerRepositoryV1PortTypeChannel : Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.4")]
    public partial class comporiPriceDiscountCustomerRepositoryV1PortTypeClient : System.ServiceModel.ClientBase<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType>, Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType
    {
        
        /// <summary>
        /// Implementieren Sie diese partielle Methode, um den Dienstendpunkt zu konfigurieren.
        /// </summary>
        /// <param name="serviceEndpoint">Der zu konfigurierende Endpunkt</param>
        /// <param name="clientCredentials">Die Clientanmeldeinformationen</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public comporiPriceDiscountCustomerRepositoryV1PortTypeClient() : 
                base(comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetDefaultBinding(), comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.comporiPriceDiscountCustomerRepositoryV1Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountCustomerRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountCustomerRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountCustomerRepositoryV1PortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public comporiPriceDiscountCustomerRepositoryV1PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1SaveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveResponse1> comporiPriceDiscountCustomerRepositoryV1SaveAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveRequest comporiPriceDiscountCustomerRepositoryV1SaveRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1SaveRequest = comporiPriceDiscountCustomerRepositoryV1SaveRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1SaveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1SaveBulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkResponse1> comporiPriceDiscountCustomerRepositoryV1SaveBulkAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1SaveBulkRequest comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest = comporiPriceDiscountCustomerRepositoryV1SaveBulkRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1SaveBulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdResponse1> comporiPriceDiscountCustomerRepositoryV1GetByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetByIdRequest comporiPriceDiscountCustomerRepositoryV1GetByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1GetByIdRequest = comporiPriceDiscountCustomerRepositoryV1GetByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1GetListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListResponse1> comporiPriceDiscountCustomerRepositoryV1GetListAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1GetListRequest comporiPriceDiscountCustomerRepositoryV1GetListRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1GetListRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1GetListRequest = comporiPriceDiscountCustomerRepositoryV1GetListRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1GetListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteResponse1> comporiPriceDiscountCustomerRepositoryV1DeleteAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteRequest comporiPriceDiscountCustomerRepositoryV1DeleteRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1DeleteRequest = comporiPriceDiscountCustomerRepositoryV1DeleteRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1> Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType.comporiPriceDiscountCustomerRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1 request)
        {
            return base.Channel.comporiPriceDiscountCustomerRepositoryV1DeleteByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdResponse1> comporiPriceDiscountCustomerRepositoryV1DeleteByIdAsync(Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.ComporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest)
        {
            Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1 inValue = new Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest1();
            inValue.comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest = comporiPriceDiscountCustomerRepositoryV1DeleteByIdRequest;
            return ((Compori.MagentoApi.SoapClient.RemoteServices.ComporiPrice.ResourceModel.ComporiPriceDiscountCustomerRepositoryV1.comporiPriceDiscountCustomerRepositoryV1PortType)(this)).comporiPriceDiscountCustomerRepositoryV1DeleteByIdAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountCustomerRepositoryV1Port))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.comporiPriceDiscountCustomerRepositoryV1Port))
            {
                return new System.ServiceModel.EndpointAddress("http://monnier.cidev04.test/wille-shop2/soap/default?services=comporiPriceDiscoun" +
                        "tCustomerRepositoryV1");
            }
            throw new System.InvalidOperationException(string.Format("Es wurde kein Endpunkt mit dem Namen \"{0}\" gefunden.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetBindingForEndpoint(EndpointConfiguration.comporiPriceDiscountCustomerRepositoryV1Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return comporiPriceDiscountCustomerRepositoryV1PortTypeClient.GetEndpointAddress(EndpointConfiguration.comporiPriceDiscountCustomerRepositoryV1Port);
        }
        
        public enum EndpointConfiguration
        {
            
            comporiPriceDiscountCustomerRepositoryV1Port,
        }
    }
}
